spring:
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

